### ISSUE TITLE
How do I remove the hacks in Stabfish.io?

### ISSUE THREAD

**Issue by eletrickball** [ZackiBoiz/Stabfish-Hacks#1]
MY FRIEND CLICKED THIS HACK FOR ME AND I NEED TO REMOVE IT PLS HELP!!!

**Comment by ZackiBoiz** [comment]
Just tell them to reload the page. All hacks ware off after a page refresh, or page close

**Comment by eletrickball** [comment]
It doesn’t work

**Comment by eletrickball** [comment]
He uses ipad

**Comment by eletrickball** [comment]
It’s permanent

**Comment by ZackiBoiz** [comment]
It shouldn't be. Send a video of it not working.

**Comment by eletrickball** [comment]
https://user-images.githubusercontent.com/99839457/216500227-35f11001-daa4-47f9-9ac8-3c5f43b3d938.MOV

**Comment by ZackiBoiz** [comment]
Oh! Yes, Stabfish1 is permanent, as it sets the `localStorage`. The only way (right now) to delete the data, is to clear the cache or localStorage.

**Comment by eletrickball** [comment]
How do I do that?

**Comment by ZackiBoiz** [comment]
[here](https://support.apple.com/guide/ipad/clear-your-cache-ipad0bb843d8/ipados)

**Comment by eletrickball** [comment]
Bad news: I’m using a school iPad, and they restrict clearing website history…

**Comment by ZackiBoiz** [comment]
I don't use an iPad, so I wouldn't know how to fix this... Sorry!

**Comment by eletrickball** [comment]
It’s okay, thanks anyway!

**Comment by ZackiBoiz** [comment]
No problem.

**Comment by ZackiBoiz** [comment]
Pinned because I'm sure many other people will be confused too.

**Comment by AVS-Memer** [comment]
How would I remove the hack if I used it on a Stabfish account?

**Comment by ZackiBoiz** [comment]
Talking about `Stabfish2.io`, those hacks should be temporary, meaning after a quick refresh or page leave, they will not be active anymore. On the other hand, if you're talking about `Stabfish.io (v1)`, the `Unlock-All-Stats` hack sets your `localStorage`, which is not very reverseable. If you would like to reset your data, you can clear your cache or just the `localStorage` to do so.

**Comment by AVS-Memer** [comment]
It was on stabfish.io
I tried that, but when I logged back onto the account, it still had the same stats

**Comment by AVS-Memer** [comment]
What does the localStorage contain? Perhaps knowing that would help restoring my original bodies

**Comment by AVS-Memer** [comment]
How do you get the code to stay after reloading?
Any code I try seems to reset after reloading

**Comment by ZackiBoiz** [comment]
Whoopsies! Sorry for the long pause. To keep the hack running on every page load, you may want to use a script manager like **Tampermonkey**, etc. Script managers make it easy to run scripts on page load.
