### ISSUE TITLE
Stabfish2.io Working the Same

### ISSUE THREAD

**Issue by Coding-Slant** [ZackiBoiz/Stabfish-Hacks#3]
Uh when i copy and paste the stabfish2.io hacks
var lcs = JSON.parse(localStorage.getItem('stabfishLocalSettings'));
lcs.bgm = Number(prompt("Enter a value (0-1 is normal)", 100));
lcs.sfx = Number(prompt("Enter a value (0-1 is normal)", 100));
localStorage.setItem('stabfishLocalSettings', JSON.stringify(lcs));
window.location.reload();

it doesnt do anything... i wont be able to respond here so could u respond on discord, Eggy#6091

**Comment by Coding-Slant** [comment]
pls help

**Comment by Coding-Slant** [comment]
oops i iddnt mean to close

**Comment by Coding-Slant** [comment]
it just messes up the music track

**Comment by ZackiBoiz** [comment]
Can you explain with detail?

**Comment by ZackiBoiz** [comment]
The hack changes the volume over the limit

**Comment by Suryas-Game** [comment]
hello I have a question how do I use stabfish 2 hacks they don't work

**Comment by Suryas-Game** [comment]
pls help
