### ISSUE TITLE
How do you open the developer console on stabfish?

### ISSUE THREAD

**Issue by sadasdwabgfg** [ZackiBoiz/Stabfish-Hacks#5]
How do you open the developer console on stabfish?

**Comment by sadasdwabgfg** [comment]
@ZackiBoiz

**Comment by itschesstime** [comment]
RightClick then inspect element.
(Ps. The dev saw these hacks and is banning all players currently using it.)

**Comment by ZackiBoiz** [comment]
ctrl + shift + j
